# Generated by Django 3.1.7 on 2021-03-22 20:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20210321_2038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 3, 22, 20, 51, 19, 275460, tzinfo=utc)
            ),
        ),
    ]
