# Generated by Django 3.1.7 on 2021-03-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_auto_20210322_2212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
